from enum import StrEnum


class RunStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEME_GENERATING = "SCHEME_GENERATING"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    PLANNING = "PLANNING"
    RUNNING = "RUNNING"
    REVIEW = "REVIEW"
    PROVING = "PROVING"
    RELEASED = "RELEASED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    WAITING = "WAITING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_FOR_CAPABILITY = "WAITING_FOR_CAPABILITY"
    SELF_CORRECTING = "SELF_CORRECTING"
    BLOCKED = "BLOCKED"
    REVIEW = "REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CAPABILITY_BUILD_FAILED = "CAPABILITY_BUILD_FAILED"
    CANCELLED = "CANCELLED"


class TaskOrigin(StrEnum):
    PLAN = "PLAN"
    REPLAN = "REPLAN"
    REVIEW_FIX = "REVIEW_FIX"


class CapabilityBackend(StrEnum):
    NATIVE = "NATIVE"
    MCP = "MCP"
    GENERATED = "GENERATED"


class CapabilityLifecycle(StrEnum):
    GAP_DETECTED = "GAP_DETECTED"
    SPEC_APPROVED = "SPEC_APPROVED"
    GENERATED = "GENERATED"
    STATIC_VALIDATED = "STATIC_VALIDATED"
    SANDBOX_TESTED = "SANDBOX_TESTED"
    FINANCIAL_VALIDATED = "FINANCIAL_VALIDATED"
    TASK_APPROVED = "TASK_APPROVED"
    ACTIVE_FOR_SCOPE = "ACTIVE_FOR_SCOPE"
    STATIC_REJECTED = "STATIC_REJECTED"
    TEST_FAILED = "TEST_FAILED"
    FINANCIAL_VALIDATION_FAILED = "FINANCIAL_VALIDATION_FAILED"
    BUILD_FAILED = "BUILD_FAILED"


class CapabilityScope(StrEnum):
    TASK = "TASK"
    RUN = "RUN"


class EvidenceStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"
    PARTIAL = "PARTIAL"


class EvidenceCategory(StrEnum):
    COMPANY_PROFILE = "COMPANY_PROFILE"
    FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT"
    MARKET = "MARKET"
    PEER = "PEER"
    NEWS = "NEWS"
    ANALYST = "ANALYST"
    TRANSCRIPT = "TRANSCRIPT"
    OTHER = "OTHER"


class EvidenceAcquisitionStatus(StrEnum):
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    ENTITLEMENT_BLOCKED = "ENTITLEMENT_BLOCKED"
    FAILED = "FAILED"


class ReviewStatus(StrEnum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


class ProofStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED_PENDING = "REQUIRED_PENDING"
    PROVING = "PROVING"
    VALID = "VALID"
    INVALID = "INVALID"
    ERROR = "ERROR"
    UNSUPPORTED = "UNSUPPORTED"
    # Phase 1/2 values remain readable for backward-compatible persisted records.
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class ProofRequirement(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    MUST_PROVE = "MUST_PROVE"


class CalculationStatus(StrEnum):
    PASS = "PASS"
    FAILED = "FAILED"


class ReplanDecision(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class CorrectionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
