from enum import StrEnum


class RunStatus(StrEnum):
    DRAFT = "DRAFT"
    SCHEME_GENERATING = "SCHEME_GENERATING"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    PLANNING = "PLANNING"
    RUNNING = "RUNNING"
    REVIEW = "REVIEW"
    PROVING = "PROVING"
    RELEASED = "RELEASED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskStatus(StrEnum):
    CREATED = "CREATED"
    WAITING = "WAITING"
    READY = "READY"
    RUNNING = "RUNNING"
    WAITING_FOR_CAPABILITY = "WAITING_FOR_CAPABILITY"
    SELF_CORRECTING = "SELF_CORRECTING"
    BLOCKED = "BLOCKED"
    REVIEW = "REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CAPABILITY_BUILD_FAILED = "CAPABILITY_BUILD_FAILED"
    CANCELLED = "CANCELLED"


class TaskOrigin(StrEnum):
    PLAN = "PLAN"
    REPLAN = "REPLAN"
    REVIEW_FIX = "REVIEW_FIX"


class CapabilityBackend(StrEnum):
    NATIVE = "NATIVE"
    MCP = "MCP"
    GENERATED = "GENERATED"


class CapabilityLifecycle(StrEnum):
    GAP_DETECTED = "GAP_DETECTED"
    SPEC_APPROVED = "SPEC_APPROVED"
    GENERATED = "GENERATED"
    STATIC_VALIDATED = "STATIC_VALIDATED"
    SANDBOX_TESTED = "SANDBOX_TESTED"
    FINANCIAL_VALIDATED = "FINANCIAL_VALIDATED"
    TASK_APPROVED = "TASK_APPROVED"
    ACTIVE_FOR_SCOPE = "ACTIVE_FOR_SCOPE"
    STATIC_REJECTED = "STATIC_REJECTED"
    TEST_FAILED = "TEST_FAILED"
    FINANCIAL_VALIDATION_FAILED = "FINANCIAL_VALIDATION_FAILED"
    BUILD_FAILED = "BUILD_FAILED"


class CapabilityScope(StrEnum):
    TASK = "TASK"
    RUN = "RUN"


class CapabilityValidationScope(StrEnum):
    PRE_ACTIVATION = "PRE_ACTIVATION"
    LIVE_RUNTIME = "LIVE_RUNTIME"


class ValidationResult(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"


class EvidenceStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    CONFLICT = "CONFLICT"
    REJECTED = "REJECTED"
    PARTIAL = "PARTIAL"


class EvidenceCategory(StrEnum):
    COMPANY_PROFILE = "COMPANY_PROFILE"
    FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT"
    MARKET = "MARKET"
    PEER = "PEER"
    NEWS = "NEWS"
    ANALYST = "ANALYST"
    TRANSCRIPT = "TRANSCRIPT"
    OTHER = "OTHER"


class EvidenceAcquisitionStatus(StrEnum):
    COMPLETED = "COMPLETED"
    PARTIAL = "PARTIAL"
    ENTITLEMENT_BLOCKED = "ENTITLEMENT_BLOCKED"
    FAILED = "FAILED"


class ReviewStatus(StrEnum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


class ProofStatus(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    REQUIRED_PENDING = "REQUIRED_PENDING"
    PROVING = "PROVING"
    VALID = "VALID"
    INVALID = "INVALID"
    ERROR = "ERROR"
    UNSUPPORTED = "UNSUPPORTED"
    # Phase 1/2 values remain readable for backward-compatible persisted records.
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class ProofRequirement(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"
    MUST_PROVE = "MUST_PROVE"


class CalculationStatus(StrEnum):
    PASS = "PASS"
    FAILED = "FAILED"


class FinancialPeriodBasis(StrEnum):
    FY = "FY"
    QUARTER = "QUARTER"
    TTM = "TTM"
    LTM = "LTM"
    CURRENT = "CURRENT"
    DAILY = "DAILY"


class FinancialActuality(StrEnum):
    UNKNOWN = "UNKNOWN"
    ACTUAL = "ACTUAL"
    ESTIMATE = "ESTIMATE"


class FinancialUnit(StrEnum):
    RATIO = "RATIO"
    PERCENT = "PERCENT"
    CURRENCY = "CURRENCY"
    COUNT = "COUNT"
    SHARES = "SHARES"
    INDEX = "INDEX"
    MULTIPLE = "MULTIPLE"


class MaterialCalculationDispositionStatus(StrEnum):
    REPORTABLE = "REPORTABLE"
    NON_REPORTABLE = "NON_REPORTABLE"


class SourceCoverageStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    BLOCKED = "BLOCKED"
    EMPTY = "EMPTY"
    ERROR = "ERROR"


class TechnicalPriceBasis(StrEnum):
    ADJUSTED_CLOSE = "ADJUSTED_CLOSE"
    RAW_CLOSE = "RAW_CLOSE"


class CorporateActionStatus(StrEnum):
    NONE_DETECTED = "NONE_DETECTED"
    RESOLVED = "RESOLVED"
    UNRESOLVED = "UNRESOLVED"
    UNASSESSED = "UNASSESSED"


class CashFlowSignConvention(StrEnum):
    OUTFLOW_NEGATIVE = "OUTFLOW_NEGATIVE"
    OUTFLOW_POSITIVE = "OUTFLOW_POSITIVE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNKNOWN = "UNKNOWN"


class OperatingMode(StrEnum):
    PUBLIC_NETWORK_MODE = "PUBLIC_NETWORK_MODE"
    LIMITED_NETWORK_MODE = "LIMITED_NETWORK_MODE"
    OFFLINE_DEMO_MODE = "OFFLINE_DEMO_MODE"


class ReplanDecision(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class CorrectionStatus(StrEnum):
    RESOLVED = "RESOLVED"
    FAILED = "FAILED"
    ESCALATED = "ESCALATED"
