import type { ResearchRun } from "../types/domain";
import { RUN_STATUS_META as statusMeta } from "../state/status";
import "../styles/workspace-pages.css";

export function ResearchRunsPage({ runs, objectCount, onCreate, onOpen }: { runs: ResearchRun[]; objectCount: number; onCreate: () => void; onOpen: (run: ResearchRun) => void }) {
  const active = runs.filter((run) => ["PLANNING", "RESEARCHING", "REVIEWING", "GENERATING_REPORT", "RESULT_PREPARING"].includes(run.status)).length;
  return <section className="workspace-page"><div className="page-head"><div><div className="breadcrumb breadcrumb-context">Research / 任务列表</div><h1 className="page-title">研究任务</h1><div className="page-sub">六个正式 Demo scenario 与 regression Run 均读取 authoritative Current Run Projection。</div></div><button className="btn primary" onClick={onCreate}>+ 新建研究任务</button></div><div className="run-kpis"><Kpi label="进行中" value={active} foot="正在执行研究" /><Kpi label="需要处理" value={runs.filter((run) => run.status === "ACTION_REQUIRED").length} foot="等待用户操作" /><Kpi label="已完成" value={runs.filter((run) => run.status === "COMPLETED").length} foot="研究结果可查看" /><Kpi label="研究对象" value={objectCount} foot="长期跟踪公司" /></div>{runs.length === 0 ? <div className="card empty-state" role="status">尚无 Research Run。点击“新建研究任务”开始。</div> : <div className="run-list">{runs.map((run) => { const meta = statusMeta[run.status]; return <button className="card run-card" key={run.id} onClick={() => onOpen(run)}><span className="run-card-primary"><span className={`badge ${meta.color}`}><span className={`dot ${run.status === "RESEARCHING" ? "pulse" : ""}`} />{meta.label}</span><span className="micro">{run.id} · {run.symbol}</span><span className="run-title">{run.company} · {run.title}</span><span className="run-meta">{run.goal}</span><span className="scenario-label">{run.scenarioId} · {run.mode}</span></span><span className="optional"><span className="stage">{run.currentActivity ?? run.stage}</span><span className="progress" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={run.progress}><i style={{ width: `${run.progress}%` }} /></span><span className="stage-sub">{run.progress}%</span></span><span className="optional"><span className="stage">Graph v{run.graphVersion}</span><span className="stage-sub">{new Date(run.updatedAt).toLocaleString("zh-CN", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</span></span><span className={`btn sm ${run.status === "COMPLETED" ? "primary" : ""}`}>{run.status === "COMPLETED" ? "查看结果" : "打开任务"}</span></button>; })}</div>}</section>;
}
function Kpi({ label, value, foot }: { label: string; value: number; foot: string }) { return <div className="card kpi"><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div><div className="kpi-foot">{foot}</div></div>; }
